### ISSUE TITLE
further import of collected data

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-schema#17]
After https://github.com/MSFREACH/msf-reach/issues/179 is resolved

**Comment by LucieGueuning** [comment]
Milestone: Phase 2a

**Comment by matthewberryman** [comment]
@LucieGueuning can you please let me know
1. If the duplicate finding algorithm was helpful or fine tuning.
2. When you have resolved the duplicate issues.
3. If it's possible for you to find addresses for all contacts? c.f. https://github.com/MSFREACH/msf-reach/issues/217

**Comment by matthewberryman** [comment]
@LucieGueuning if it helps with duplicates, as well as changing the parameter that defines how close a match it needs to be before being flagged as a duplicate, I could also update my software to add a column indicating what entry (line number) it matched with.

**Comment by LucieGueuning** [comment]
As mentionned, by skype. I am ok with that. 
I continue to clean data, it is not yet done. 

1. it was helpful, it is almost done (all except for Natasha contacts)
2. End of next week I would say. I am a bit overwhelmed. 
3. I try to do my best. If it is impossible. cf. SOL for #217
