### ISSUE TITLE
bringing in extra osm data

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-schema#28]
Athena table setup:
https://gist.github.com/matthewberryman/729f1db6a485d604a96a80eed450b5fb
Example water tap query:
https://gist.github.com/matthewberryman/8c50fa774f55e330f219a0769d98028a

Possible pipeline:
SNS ( ARN: arn:aws:sns:us-east-1:800218804198:New_File ) -> AWS Lambda function ( derived from https://github.com/burtcorp/athena-runner ) for running query -> s3 -> AWS Lambda function for uploading to Mapbox via [Mapbox API](https://www.mapbox.com/api-documentation/).

**Comment by LucieGueuning** [comment]
FYI, I am working with some developers to improve the Humanitarian layer from OSM to include all the items we would like.

I will keep you posted regarding to that.

**Comment by matthewberryman** [comment]
Negated with work with HOT and display of that layer
