### ISSUE TITLE
update for event metadata notification

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-schema#29]
Script to turn this into a list of 
```json
{"updated": time, "notification": "latest_notification"}
```

**Comment by matthewberryman** [comment]
@talltom I'm out of time today - can you please take a look at syntax overnight my time?
currently throws syntax error
```
psql:update_notifications.sql:1: ERROR:  syntax error at or near "select"
LINE 1: ...etadata || jsonb_build_object('notification_time',select ext...
```

**Comment by talltom** [comment]
@matthewberryman try this?
https://github.com/MSFREACH/msf-reach-schema/commit/981cc493f7a2e5db5c5bc5e8731a22abb7cb98df
