### ISSUE TITLE
latest contact import

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-schema#37]
On the latest import just noting that:
* Is "Phone Number (fix)" for your working to fix the phone entries, or a typo on "Phone number (fax)"?
* Anything that doesn't exactly match the categories as defined, with exception of "Non-Governmental Organization"  that I will map onto "Other NGO" or where I can infer from other fields that someone is  "Current MSF Staff", then I will put in "Other" as the category, and there will be a lot of "Other"
* Importing via a script provides no validation of entries, e.g. if there's a typo on "male", say "mle" then it goes in as that, same if there's a typo in date of birth, and there's no checking to make sure phone numbers are valid (against the inbuilt database used).
* I will put in OC field as text, there are way too many variations to map it onto one of the predefined options.
* There are other MSF fields we'd set up for which there's no info / I cannot invest the time to process the text to figure it out.

I will do my best effort for now but really these are best put in through the interface at some point for consistence and completeness.

**Comment by LucieGueuning** [comment]
1. I changed to 'Phone Number (work) 2'. Can be considered as Phone Number (work) if there is no number yet, otherwise need to be considered as 'Other Phone Number'. Same comment for 'Phone Number (Mobile) 2'. I will update the list to make it easier. 
2. I will update the list to make it matched with the defined categories. 
3. Could you please flag those mistake typo. I will correct them to make it more clean on REACH. 
4. I will update the list with the right typo for each OC.
5. unclear what you meant. could you please be clearer? 

If I want to update info, can I do it on the spreadsheet shared or it is useless because of importation already. Please let me know for further actions on my side. Thanks

**Comment by LucieGueuning** [comment]
- date of birth
- male/female
- Dr Maria Network (defined category)
- Phone number
- OC typo

**Comment by LucieGueuning** [comment]
@matthewberryman, for the category which is not matching with defined category, please make them and Other, and then fill the field 'define' by the info of the spreadsheet. Thanks.

**Comment by LucieGueuning** [comment]
All done, you can import

**Comment by matthewberryman** [comment]
@LucieGueuning wow that is much cleaner and is looking good on some early testing I am doing on my computer. I have one bug to fix later today, then I need to merge in with the existing in the database (ETA tomorrow my time).

**Comment by LucieGueuning** [comment]
https://docs.google.com/spreadsheets/d/1zuIPBTOPsrSzZ2C7xPe-vxcNLhrJJ6qOXtyVmI0LHxo/edit?ts=59000e84#gid=386702821

Ok, so now (Wednesday 14.03 at 11.29), **all data are cleaned**. This is the last time that I touch this spreadsheet. Please take into consideration the following items when importation: 
- **All information** need to be display on REACH
- **All contact** need to be upload on REACH (**+**contact from the contact card of REACH)
- **Time stamp** need to be display as 'created on'
- **Private** contact need to be only shown for Maria Guevara profile, with the ability to share it publicly if she wants to. 
- Type of contact: **Association** and **MSF Peers** info needs to extract from the 'type of contact' row.

**Comment by matthewberryman** [comment]
*   All information need to be display on REACH

  *   All contact need to be upload on REACH (**+**contact from the contact card of REACH)

Noted but per previously defined landing and events page we do not display contacts with no location. On landing page we have the map only and on the event page we have a table but it synchronises with the map.

  *   Time stamp need to be display as 'created on'

Ok. I will set the separate updated_at field to be current time stamp (otherwise I have no easy way of identifying them for removal on future reimport).

  *   Private contact need to be only shown for Maria Guevara profile, with the ability to share it publicly if she wants to.

Ok we haven’t previously talked about restricting showing contacts on a per operator basis so this feature request will need to be raised and then completed before I can add those contacts then.

  *   Type of contact: Association and MSF Peers info needs to extract from the 'type of contact' row.

I will do my best on Association (not consistent as sometimes it’s “Asso” and other times “Association” but those seems to capture most cases). I’ve already got some code written for peers.

Sent from my iPhone

On 14 Mar 2018, at 22:34, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:

  *   All information need to be display on REACH
  *   All contact need to be upload on REACH (**+**contact from the contact card of REACH)
  *   Time stamp need to be display as 'created on'
  *   Private contact need to be only shown for Maria Guevara profile, with the ability to share it publicly if she wants to.
  *   Type of contact: Association and MSF Peers info needs to extract from the 'type of contact' row.

**Comment by matthewberryman** [comment]
One issue I've found is that "United Nations" is in most cases written as "United Nation", which then breaks the search filter I wrote. I am just about to update the code with a patch (following some testing) for that to avoid having you do a lot of extra cleaning on your part. Then with some other tidy up I believe we're ready to go. In between above extra work plus other tasks today (incl. checking in with Mehrdad on some of his work) I'm now out of time today to get this into the database, but I will be up early tomorrow my time to get this in @LucieGueuning

**Comment by LucieGueuning** [comment]
Hi Matthew, I have changed all the United Nation to United Nations on excel file. Any other issues to be fixed, cleaned?

**Comment by matthewberryman** [comment]
No, that was the main one but per my previous comment you didn’t need to do it my software automatically handles both—sorry if that was not clear.

Sent from my iPhone

On 15 Mar 2018, at 21:55, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Matthew, I have changed all the United Nation to United Nations on excel file. Any other issues to be fixed, cleaned?

**Comment by matthewberryman** [comment]
https://github.com/MSFREACH/msf-reach-schema/pull/38#issuecomment-373541806
