### ISSUE TITLE
Private/public contact based on Active Directory

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-schema#41]
schema changes for https://github.com/MSFREACH/msf-reach/issues/332

**Comment by matthewberryman** [comment]
cc @LucieGueuning this needs some minor database tweaks but I believe https://github.com/MSFREACH/msf-reach-schema/commit/4195c95158a1595babba2f8c96c06d5de5d43379 should cover it—I will still need to test this though.

**Comment by LucieGueuning** [comment]
How can I test it? I can't see the private contact of Maria right? 

Can I add one private contact to my profile?

**Comment by matthewberryman** [comment]
I haven’t put any private contacts in to the database yet.

From the contact cards if you tick the new box to keep it private then it can only be seen by you.

Sent from my iPhone

On 16 Apr 2018, at 20:01, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


How can I test it? I can't see the private contact of Maria right?

Can I add one private contact to my profile?

**Comment by LucieGueuning** [comment]
All the contacts from the spreadsheet who are private are the one from Maria. Could you please ensure that this is linked and private to her account? thanks

**Comment by LucieGueuning** [comment]
- need to be able to share this contact with another specific MSF staff
- need to see which contacts is private and public (UI to be suggested by @anexact)
- need to be able to put the private contact to public and vice-versa

**Comment by matthewberryman** [comment]
@LucieGueuning I didn't put Maria's private contacts in in the first place before this feature was added, in order to keep them private. Now this feature is in place I will reach out to Maria - I need her to put in one (just one) manually first so I can get her ID number in the system for importing.
