### ISSUE TITLE
import speciality from data supplied

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-schema#8]
https://github.com/MSFREACH/msf-reach/issues/102

**Comment by matthewberryman** [comment]
No speciality data is supplied in the spreadsheet. cc @clgeros @LucieGueuning

**Comment by LucieGueuning** [comment]
Don't understand what this issue is about. When you have time, could you please highlight me? 
@matthewberryman @clgeros

**Comment by matthewberryman** [comment]
@LucieGueuning in https://github.com/MSFREACH/msf-reach/issues/102 we were asked to add a speciality field to display, however
1. We weren't capturing that on contact entry, which I fixed in https://github.com/MSFREACH/msf-reach/issues/114 , and
2. I opened this issue for myself to check the supplied contact data from Google Drive, to see if it had any relevant column and if so I could use that, however I couldn't find anything, so I have closed this separate but related issue.
